[package]
name = "crustacean-states"
version = "0.1.0"
edition = "2021"
authors = ["Trisk (Aramos)"]
description = "A NationStates API wrapper designed for ease of use"

publish = false

[dependencies]
dotenv = "0.15.0"
itertools = "0.10.5"
quick-xml = { version = "0.28.2", features = ["async-tokio", "serialize"] }
reqwest = "0.11.18"
serde = { version = "1.0.163", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }
thiserror = "1.0.40"
